import type {
  ApartmentEntity,
  BookingEntity,
  EntityStore,
  GateLogEntity,
  InvitationEntity,
  MarketItemEntity,
  NoticeEntity,
  UserEntity,
} from "../types.js";

const now = new Date().toISOString();
const societyId = "soc-001";

export const db: EntityStore = {
  users: [
    {
      id: "usr-admin-001",
      societyId,
      fullName: "Planet Admin",
      email: "admin@planet.app",
      phone: "9999999999",
      role: "Admin",
      status: "Active",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "usr-sec-001",
      societyId,
      fullName: "Security Desk",
      email: "security@planet.app",
      phone: "9888888888",
      role: "Security",
      status: "Active",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "usr-res-001",
      societyId,
      fullName: "Andrea Resident",
      email: "andrea@planet.app",
      phone: "9777777777",
      role: "Resident",
      status: "Active",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "usr-res-002",
      societyId,
      fullName: "Karan Resident",
      email: "karan@planet.app",
      phone: "9666666666",
      role: "Resident",
      status: "Active",
      createdAt: now,
      updatedAt: now,
    },
  ] as UserEntity[],
  apartments: [
    {
      id: "apt-a-102",
      societyId,
      tower: "A",
      unitNumber: "102",
      floor: 1,
      occupancyStatus: "Occupied",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "apt-b-203",
      societyId,
      tower: "B",
      unitNumber: "203",
      floor: 2,
      occupancyStatus: "Occupied",
      createdAt: now,
      updatedAt: now,
    },
  ] as ApartmentEntity[],
  gateLogs: [] as GateLogEntity[],
  invitations: [] as InvitationEntity[],
  bookings: [
    {
      id: "book-activity-001",
      societyId,
      requesterUserId: "usr-res-001",
      apartmentId: "apt-a-102",
      authorName: "Shanta Bai",
      eventType: "Birthday",
      spaceType: "Community Hall",
      visibility: "Public",
      message: "Birthday celebration with neighbors.",
      bookingDate: "2026-04-10",
      startTime: "18:00",
      endTime: "20:00",
      paymentLabel: "A-101",
      paymentStatus: "Unpaid",
      paymentMethod: "Razorpay",
      status: "ToCheck",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "book-activity-002",
      societyId,
      requesterUserId: "usr-res-002",
      apartmentId: "apt-b-203",
      authorName: "Karan Resident",
      eventType: "Yoga Workshop",
      spaceType: "Gym",
      visibility: "Public",
      message: "Morning yoga workshop for residents.",
      bookingDate: "2026-04-11",
      startTime: "07:00",
      endTime: "08:30",
      paymentLabel: "B-203",
      paymentStatus: "Unpaid",
      paymentMethod: "Razorpay",
      status: "ToCheck",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "book-activity-007",
      societyId,
      requesterUserId: "usr-res-001",
      apartmentId: "apt-a-102",
      authorName: "Andrea Resident",
      eventType: "Kids Art Class",
      spaceType: "Co-Work Space",
      visibility: "Private",
      message: "Private art class booking.",
      bookingDate: "2026-04-12",
      startTime: "11:00",
      endTime: "12:30",
      paymentLabel: "A-102",
      paymentStatus: "Unpaid",
      paymentMethod: "Razorpay",
      status: "ToCheck",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "book-activity-003",
      societyId,
      requesterUserId: "usr-res-001",
      apartmentId: "apt-a-102",
      authorName: "Shanta Bai",
      eventType: "Anniversary",
      spaceType: "Community Hall",
      visibility: "Public",
      message: "Anniversary dinner booking.",
      bookingDate: "2026-04-14",
      startTime: "19:00",
      endTime: "21:00",
      paymentLabel: "A-101",
      paymentStatus: "Paid",
      paymentMethod: "Razorpay",
      status: "Approved",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "book-activity-004",
      societyId,
      requesterUserId: "usr-res-002",
      apartmentId: "apt-b-203",
      authorName: "Test Resident",
      eventType: "Ganesh Festival",
      spaceType: "Community Hall",
      visibility: "Public",
      message: "Festival activity request.",
      bookingDate: "2026-04-20",
      startTime: "10:00",
      endTime: "13:00",
      paymentLabel: "A-101",
      paymentStatus: "Unpaid",
      paymentMethod: "Razorpay",
      status: "ToPay",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "book-activity-005",
      societyId,
      requesterUserId: "usr-res-001",
      apartmentId: "apt-a-102",
      authorName: "Shanta Bai",
      eventType: "Christmas",
      spaceType: "Community Hall",
      visibility: "Public",
      message: "Seasonal activity.",
      bookingDate: "2026-04-24",
      startTime: "17:30",
      endTime: "19:30",
      paymentLabel: "A-101",
      paymentStatus: "Unpaid",
      paymentMethod: "Razorpay",
      status: "Rejected",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "book-activity-006",
      societyId,
      requesterUserId: "usr-res-001",
      apartmentId: "apt-a-102",
      authorName: "Shanta Bai",
      eventType: "Christmas",
      spaceType: "Community Hall",
      visibility: "Public",
      message: "Refund request for cancelled event.",
      bookingDate: "2026-04-28",
      startTime: "16:00",
      endTime: "18:00",
      paymentLabel: "A-101",
      paymentStatus: "RefundInitiated",
      paymentMethod: "Razorpay",
      status: "Refund",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "book-activity-008",
      societyId,
      requesterUserId: "usr-res-001",
      apartmentId: "apt-a-102",
      authorName: "Shanta Bai",
      eventType: "Christmas",
      spaceType: "Community Hall",
      visibility: "Public",
      message: "Refund completed activity.",
      bookingDate: "2026-04-30",
      startTime: "15:00",
      endTime: "17:00",
      paymentLabel: "A-101",
      paymentStatus: "Refunded",
      paymentMethod: "Razorpay",
      status: "Refunded",
      createdAt: now,
      updatedAt: now,
    },
  ] as BookingEntity[],
  notices: [] as NoticeEntity[],
  marketItems: [] as MarketItemEntity[],
};

export const apartmentUserMap: Array<{
  id: string;
  apartmentId: string;
  userId: string;
  relationshipType: "Owner" | "Tenant" | "FamilyMember" | "Staff";
  status: "Active" | "Inactive";
  createdAt: string;
  updatedAt: string;
}> = [
  {
    id: "uam-001",
    apartmentId: "apt-a-102",
    userId: "usr-res-001",
    relationshipType: "Owner",
    status: "Active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "uam-002",
    apartmentId: "apt-b-203",
    userId: "usr-res-002",
    relationshipType: "Tenant",
    status: "Active",
    createdAt: now,
    updatedAt: now,
  },
];
